<script lang="ts">
  import { onMount } from 'svelte';
  import Icon from '$lib/components/Icon.svelte';
  
  let loading = false;
  let synapses = [];
  
  // Placeholder data structure for AI synapses
  interface Synapse {
    id: string;
    title: string;
    type: 'connection' | 'learning_path' | 'insight' | 'recommendation';
    content: string;
    source_items: Array<{id: string, title: string, url?: string}>;
    strength: number; // 1-10
    created_at: string;
    tags: string[];
  }
  
  // Sample data for demonstration
  const sampleSynapses: Synapse[] = [
    {
      id: '1',
      title: 'React + TypeScript Learning Path',
      type: 'learning_path',
      content: 'Based on your JavaScript knowledge and interest in frontend development, here\'s a structured path to master React with TypeScript.',
      source_items: [
        {id: '1', title: 'JavaScript ES6 Guide', url: 'https://example.com'},
        {id: '2', title: 'React Documentation'},
        {id: '3', title: 'TypeScript Handbook'}
      ],
      strength: 9,
      created_at: '2025-01-10T10:00:00Z',
      tags: ['react', 'typescript', 'frontend', 'learning']
    },
    {
      id: '2',
      title: 'API Design Pattern Connection',
      type: 'connection',
      content: 'Your REST API documentation connects with GraphQL concepts. Consider exploring GraphQL for more flexible data fetching.',
      source_items: [
        {id: '4', title: 'REST API Best Practices'},
        {id: '5', title: 'GraphQL Introduction'}
      ],
      strength: 7,
      created_at: '2025-01-09T15:30:00Z',
      tags: ['api', 'rest', 'graphql', 'backend']
    }
  ];
  
  onMount(() => {
    // For now, use sample data
    synapses = sampleSynapses;
  });
  
  function getSynapseIcon(type: string): string {
    const icons = {
      'connection': '🔗',
      'learning_path': '🛤️',
      'insight': '💡',
      'recommendation': '🎯'
    };
    return icons[type] || '🧠';
  }
  
  function getSynapseColor(type: string): string {
    const colors = {
      'connection': '#3b82f6',
      'learning_path': '#10b981',
      'insight': '#f59e0b',
      'recommendation': '#ef4444'
    };
    return colors[type] || '#6b7280';
  }
  
  function getStrengthLabel(strength: number): string {
    if (strength >= 8) return 'Strong';
    if (strength >= 6) return 'Medium';
    if (strength >= 4) return 'Weak';
    return 'Minimal';
  }
</script>

<svelte:head>
  <title>AI Synapses - Code Cortex | PRSNL</title>
</svelte:head>

<div class="synapses-page">
  <!-- Header -->
  <div class="page-header">
    <div class="header-left">
      <a href="/code-cortex" class="back-link">
        <Icon name="arrow-left" size="small" />
        Code Cortex
      </a>
      <div class="header-content">
        <h1>🧠 AI Synapses</h1>
        <p>Intelligent connections and learning paths generated by AI</p>
      </div>
    </div>
    
    <div class="header-actions">
      <button class="generate-btn" disabled>
        <Icon name="sparkles" size="small" />
        Generate New Synapses
      </button>
    </div>
  </div>
  
  <!-- Coming Soon Notice -->
  <div class="coming-soon-banner">
    <div class="banner-icon">🚧</div>
    <div class="banner-content">
      <h3>AI Synapses Feature Coming Soon</h3>
      <p>We're developing an intelligent system that will analyze your development content and generate meaningful connections, learning paths, and insights. This feature will help you discover relationships between your documentation, identify knowledge gaps, and suggest optimal learning sequences.</p>
    </div>
  </div>
  
  <!-- Preview/Demo Section -->
  <div class="preview-section">
    <h2>🔮 Preview: What AI Synapses Will Do</h2>
    
    <div class="features-grid">
      <div class="feature-card">
        <div class="feature-icon">🔗</div>
        <h3>Smart Connections</h3>
        <p>Automatically discover relationships between your documentation, code snippets, and learning resources.</p>
      </div>
      
      <div class="feature-card">
        <div class="feature-icon">🛤️</div>
        <h3>Learning Paths</h3>
        <p>Generate personalized learning sequences based on your current knowledge and career goals.</p>
      </div>
      
      <div class="feature-card">
        <div class="feature-icon">💡</div>
        <h3>Knowledge Insights</h3>
        <p>Identify patterns in your learning, spot knowledge gaps, and suggest areas for improvement.</p>
      </div>
      
      <div class="feature-card">
        <div class="feature-icon">🎯</div>
        <h3>Smart Recommendations</h3>
        <p>Get AI-powered suggestions for relevant documentation, tools, and resources based on your projects.</p>
      </div>
    </div>
  </div>
  
  <!-- Sample Synapses (Demo) -->
  <div class="demo-section">
    <h2>📋 Sample Synapses (Demo)</h2>
    <p class="demo-note">Here's what AI-generated synapses might look like once the feature is ready:</p>
    
    <div class="synapses-grid">
      {#each sampleSynapses as synapse}
        <article class="synapse-card" style="border-left-color: {getSynapseColor(synapse.type)}">
          <div class="synapse-header">
            <div class="synapse-meta">
              <span class="synapse-type" style="background: {getSynapseColor(synapse.type)}20; color: {getSynapseColor(synapse.type)}">
                {getSynapseIcon(synapse.type)} {synapse.type.replace('_', ' ')}
              </span>
              <span class="synapse-strength strength-{Math.floor(synapse.strength / 3)}">
                {getStrengthLabel(synapse.strength)}
              </span>
            </div>
            
            <h3 class="synapse-title">{synapse.title}</h3>
          </div>
          
          <p class="synapse-content">{synapse.content}</p>
          
          <div class="source-items">
            <h4>Connected Items:</h4>
            <div class="source-list">
              {#each synapse.source_items as item}
                <div class="source-item">
                  <Icon name="file-text" size="small" />
                  <span>{item.title}</span>
                  {#if item.url}
                    <Icon name="external-link" size="small" />
                  {/if}
                </div>
              {/each}
            </div>
          </div>
          
          <div class="synapse-footer">
            <div class="synapse-tags">
              {#each synapse.tags as tag}
                <span class="tag">#{tag}</span>
              {/each}
            </div>
            <span class="synapse-date">{new Date(synapse.created_at).toLocaleDateString()}</span>
          </div>
        </article>
      {/each}
    </div>
  </div>
  
  <!-- Call to Action -->
  <div class="cta-section">
    <div class="cta-content">
      <h3>🚀 Help Shape This Feature</h3>
      <p>We're designing AI Synapses to be as useful as possible for developers. Your input will help us build something amazing!</p>
      <div class="cta-actions">
        <a href="/capture" class="cta-btn primary">Add More Content</a>
        <a href="/code-cortex" class="cta-btn secondary">Explore Other Features</a>
      </div>
    </div>
  </div>
</div>

<style>
  .synapses-page {
    max-width: 1200px;
    margin: 0 auto;
    padding: 2rem;
    color: #00ff88;
    font-family: 'JetBrains Mono', monospace;
  }
  
  .page-header {
    display: flex;
    justify-content: space-between;
    align-items: flex-start;
    margin-bottom: 2rem;
  }
  
  .header-left {
    display: flex;
    flex-direction: column;
    gap: 1rem;
  }
  
  .back-link {
    display: flex;
    align-items: center;
    gap: 0.5rem;
    color: rgba(0, 255, 136, 0.7);
    text-decoration: none;
    font-size: 0.9rem;
    transition: color 0.3s ease;
  }
  
  .back-link:hover {
    color: #00ff88;
  }
  
  .header-content h1 {
    font-size: 2rem;
    margin: 0;
    background: linear-gradient(45deg, #00ff88, #DC143C);
    -webkit-background-clip: text;
    -webkit-text-fill-color: transparent;
    background-clip: text;
  }
  
  .header-content p {
    margin: 0.5rem 0 0 0;
    opacity: 0.8;
  }
  
  .generate-btn {
    background: rgba(0, 255, 136, 0.1);
    border: 1px solid rgba(0, 255, 136, 0.3);
    color: rgba(0, 255, 136, 0.5);
    padding: 0.75rem 1.5rem;
    border-radius: 8px;
    cursor: not-allowed;
    display: flex;
    align-items: center;
    gap: 0.5rem;
    font-family: inherit;
  }
  
  .coming-soon-banner {
    background: linear-gradient(135deg, rgba(255, 165, 0, 0.1), rgba(255, 165, 0, 0.05));
    border: 1px solid rgba(255, 165, 0, 0.3);
    border-radius: 12px;
    padding: 2rem;
    margin-bottom: 3rem;
    display: flex;
    gap: 1rem;
    align-items: flex-start;
  }
  
  .banner-icon {
    font-size: 2rem;
    color: #ffa500;
  }
  
  .banner-content h3 {
    margin: 0 0 0.5rem 0;
    color: #ffa500;
    font-size: 1.25rem;
  }
  
  .banner-content p {
    margin: 0;
    opacity: 0.9;
    line-height: 1.6;
  }
  
  .preview-section, .demo-section {
    margin-bottom: 3rem;
  }
  
  .preview-section h2, .demo-section h2 {
    font-size: 1.5rem;
    margin-bottom: 1.5rem;
    color: #00ff88;
    text-transform: uppercase;
    letter-spacing: 1px;
  }
  
  .features-grid {
    display: grid;
    grid-template-columns: repeat(auto-fit, minmax(280px, 1fr));
    gap: 1.5rem;
  }
  
  .feature-card {
    background: rgba(0, 0, 0, 0.6);
    border: 1px solid rgba(0, 255, 136, 0.3);
    border-radius: 12px;
    padding: 1.5rem;
    text-align: center;
    transition: all 0.3s ease;
  }
  
  .feature-card:hover {
    border-color: #00ff88;
    transform: translateY(-2px);
    box-shadow: 0 8px 25px rgba(0, 255, 136, 0.2);
  }
  
  .feature-icon {
    font-size: 2.5rem;
    margin-bottom: 1rem;
  }
  
  .feature-card h3 {
    margin: 0 0 0.5rem 0;
    color: #00ff88;
    font-size: 1.1rem;
  }
  
  .feature-card p {
    margin: 0;
    opacity: 0.8;
    font-size: 0.9rem;
    line-height: 1.5;
  }
  
  .demo-note {
    color: rgba(0, 255, 136, 0.7);
    font-style: italic;
    margin-bottom: 2rem;
  }
  
  .synapses-grid {
    display: grid;
    grid-template-columns: repeat(auto-fit, minmax(400px, 1fr));
    gap: 1.5rem;
  }
  
  .synapse-card {
    background: rgba(0, 0, 0, 0.6);
    border: 1px solid rgba(0, 255, 136, 0.3);
    border-left: 4px solid;
    border-radius: 12px;
    padding: 1.5rem;
    transition: all 0.3s ease;
  }
  
  .synapse-card:hover {
    transform: translateY(-2px);
    box-shadow: 0 8px 25px rgba(0, 255, 136, 0.2);
  }
  
  .synapse-header {
    margin-bottom: 1rem;
  }
  
  .synapse-meta {
    display: flex;
    gap: 0.5rem;
    margin-bottom: 0.75rem;
    align-items: center;
  }
  
  .synapse-type {
    font-size: 0.75rem;
    padding: 0.25rem 0.5rem;
    border-radius: 12px;
    font-weight: 500;
    text-transform: capitalize;
  }
  
  .synapse-strength {
    font-size: 0.75rem;
    padding: 0.25rem 0.5rem;
    border-radius: 12px;
    font-weight: 500;
  }
  
  .synapse-strength.strength-3 {
    background: rgba(16, 185, 129, 0.2);
    color: #10b981;
  }
  
  .synapse-strength.strength-2 {
    background: rgba(245, 158, 11, 0.2);
    color: #f59e0b;
  }
  
  .synapse-strength.strength-1 {
    background: rgba(239, 68, 68, 0.2);
    color: #ef4444;
  }
  
  .synapse-title {
    margin: 0;
    font-size: 1.1rem;
    color: #00ff88;
  }
  
  .synapse-content {
    margin: 0 0 1rem 0;
    opacity: 0.9;
    line-height: 1.5;
  }
  
  .source-items h4 {
    margin: 0 0 0.5rem 0;
    font-size: 0.9rem;
    color: rgba(0, 255, 136, 0.8);
    text-transform: uppercase;
    letter-spacing: 0.5px;
  }
  
  .source-list {
    display: flex;
    flex-direction: column;
    gap: 0.25rem;
    margin-bottom: 1rem;
  }
  
  .source-item {
    display: flex;
    align-items: center;
    gap: 0.5rem;
    font-size: 0.875rem;
    opacity: 0.8;
  }
  
  .synapse-footer {
    display: flex;
    justify-content: space-between;
    align-items: center;
    gap: 1rem;
  }
  
  .synapse-tags {
    display: flex;
    gap: 0.5rem;
    flex-wrap: wrap;
    flex: 1;
  }
  
  .tag {
    background: rgba(0, 255, 136, 0.1);
    color: rgba(0, 255, 136, 0.8);
    padding: 0.2rem 0.5rem;
    border-radius: 4px;
    font-size: 0.75rem;
  }
  
  .synapse-date {
    font-size: 0.75rem;
    color: rgba(0, 255, 136, 0.6);
  }
  
  .cta-section {
    background: linear-gradient(135deg, rgba(0, 255, 136, 0.1), rgba(220, 20, 60, 0.1));
    border: 1px solid rgba(0, 255, 136, 0.3);
    border-radius: 12px;
    padding: 2rem;
    text-align: center;
  }
  
  .cta-content h3 {
    margin: 0 0 0.5rem 0;
    font-size: 1.5rem;
    color: #00ff88;
  }
  
  .cta-content p {
    margin: 0 0 2rem 0;
    opacity: 0.9;
    font-size: 1.1rem;
  }
  
  .cta-actions {
    display: flex;
    gap: 1rem;
    justify-content: center;
  }
  
  .cta-btn {
    padding: 0.75rem 2rem;
    border-radius: 8px;
    text-decoration: none;
    font-weight: bold;
    transition: all 0.3s ease;
    display: inline-block;
  }
  
  .cta-btn.primary {
    background: linear-gradient(45deg, #00ff88, #DC143C);
    color: black;
  }
  
  .cta-btn.primary:hover {
    transform: translateY(-2px);
  }
  
  .cta-btn.secondary {
    background: rgba(0, 255, 136, 0.1);
    border: 1px solid rgba(0, 255, 136, 0.3);
    color: #00ff88;
  }
  
  .cta-btn.secondary:hover {
    background: rgba(0, 255, 136, 0.2);
    border-color: #00ff88;
  }
  
  /* Mobile responsiveness */
  @media (max-width: 768px) {
    .synapses-page {
      padding: 1rem;
    }
    
    .page-header {
      flex-direction: column;
      gap: 1rem;
    }
    
    .features-grid {
      grid-template-columns: 1fr;
    }
    
    .synapses-grid {
      grid-template-columns: 1fr;
    }
    
    .cta-actions {
      flex-direction: column;
    }
    
    .coming-soon-banner {
      flex-direction: column;
      text-align: center;
    }
  }
</style>