version: '3.8'

services:
  db:
    image: postgres:16-alpine
    container_name: prsnl_db
    restart: unless-stopped
    environment:
      POSTGRES_DB: prsnl
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./backend/app/db/schema.sql:/docker-entrypoint-initdb.d/02-schema.sql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d prsnl"]
      interval: 10s
      timeout: 5s
      retries: 5

  backend:
    build: ./backend
    container_name: prsnl_backend
    restart: unless-stopped
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app
    depends_on:
      db:
        condition: service_healthy
      ollama:
        condition: service_started
    environment:
      DATABASE_URL: postgresql://postgres:postgres@db:5432/prsnl
      OLLAMA_BASE_URL: http://ollama:11434
      OLLAMA_MODEL: llama3

  ollama:
    image: ollama/ollama:latest
    container_name: prsnl_ollama
    restart: unless-stopped
    ports:
      - "11434:11434"
    volumes:
      - ollama_data:/root/.ollama
    deploy:
      resources:
        limits:
          memory: 4G
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:11434"]
      interval: 30s
      timeout: 10s
      retries: 5

volumes:
  postgres_data:
  ollama_data:
