# PRSNL Docker Configuration
# NOTE: We use local PostgreSQL for the main database
# This file is for Redis and other services only

services:
  # Database is now using local PostgreSQL (not Docker)
  # To use Docker database again, uncomment the db service below
  
  # db:
  #   image: pgvector/pgvector:pg16
  #   container_name: prsnl_db
  #   restart: unless-stopped
  #   environment:
  #     POSTGRES_DB: prsnl
  #     POSTGRES_USER: postgres
  #     POSTGRES_PASSWORD: postgres
  #   ports:
  #     - "${POSTGRES_PORT:-5432}:5432"
  #   volumes:
  #     - postgres_data:/var/lib/postgresql/data
  #     - ./backend/app/db/schema.sql:/docker-entrypoint-initdb.d/02-schema.sql
  #   healthcheck:
  #     test: ["CMD-SHELL", "pg_isready -U postgres -d prsnl"]
  #     interval: 10s
  #     timeout: 5s
  #     retries: 5

  # ===== LIBRECHAT SERVICES =====
  # LibreChat - Advanced Chat Interface
  librechat:
    image: ghcr.io/danny-avila/librechat-dev:latest
    container_name: prsnl_librechat
    restart: unless-stopped
    ports:
      - "${LIBRECHAT_PORT:-3080}:3080"
    depends_on:
      - librechat-mongo
      - librechat-meilisearch
    env_file:
      - ./librechat.env
    environment:
      # Override with specific PRSNL settings
      AZURE_OPENAI_API_KEY: ${AZURE_OPENAI_API_KEY}
      RAG_PGVECTOR_CONNECTION_STRING: postgresql://pronav@host.docker.internal:5433/prsnl
    volumes:
      - ./librechat.yaml:/app/librechat.yaml
      - librechat_uploads:/app/uploads
      - librechat_logs:/app/logs
    extra_hosts:
      - "host.docker.internal:host-gateway"

  # MongoDB for LibreChat data storage
  librechat-mongo:
    image: mongo:6.0
    container_name: prsnl_librechat_mongo
    restart: unless-stopped
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: ${LIBRECHAT_MONGO_PASSWORD:-secure_mongo_password}
    volumes:
      - librechat_mongo_data:/data/db
    command: mongod --noauth

  # MeiliSearch for LibreChat search functionality
  librechat-meilisearch:
    image: getmeili/meilisearch:v1.5
    container_name: prsnl_librechat_meilisearch
    restart: unless-stopped
    environment:
      MEILI_MASTER_KEY: ${LIBRECHAT_MEILI_KEY:-secure_meili_key}
      MEILI_NO_ANALYTICS: true
      MEILI_ENV: production
    volumes:
      - librechat_meili_data:/meili_data

  # LibreChat RAG API for document processing
  librechat-rag:
    image: ghcr.io/danny-avila/librechat-rag-api-dev:latest
    container_name: prsnl_librechat_rag
    restart: unless-stopped
    environment:
      RAG_PORT: 8000
      RAG_HOST: 0.0.0.0
      VECTOR_DB_TYPE: pgvector
      COLLECTION_NAME: prsnl_knowledge_base
      CHUNK_SIZE: 1500
      CHUNK_OVERLAP: 100
      RAG_PGVECTOR_CONNECTION_STRING: postgresql://pronav@host.docker.internal:5433/prsnl
      EMBEDDINGS_PROVIDER: azure
      EMBEDDINGS_MODEL: text-embedding-ada-002
      RAG_AZURE_OPENAI_ENDPOINT: https://airops.openai.azure.com
      RAG_AZURE_OPENAI_API_KEY: ${AZURE_OPENAI_API_KEY}
    volumes:
      - librechat_uploads:/app/uploads
    extra_hosts:
      - "host.docker.internal:host-gateway"

  redis:
    image: docker.dragonflydb.io/dragonflydb/dragonfly
    container_name: prsnl_redis
    restart: unless-stopped
    ports:
      - "${REDIS_PORT:-6379}:6379"
    volumes:
      - redis_data:/data
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5

  backend:
    build: ./backend
    container_name: prsnl_backend
    restart: unless-stopped
    ports:
      - "${BACKEND_PORT:-8000}:8000"
    volumes:
      - ./backend:/app
      - ./backend/media:/app/media
      - /Users/pronav/Library/Application Support/Arc:/chrome-profile:ro
    depends_on:
      # db:
      #   condition: service_healthy
      redis:
        condition: service_healthy
    environment:
      # Using local database instead of Docker
      DATABASE_URL: postgresql://pronav@host.docker.internal:5432/prsnl
      PG_CONN_STR: postgresql://postgres:postgres@db:5432/prsnl
      REDIS_URL: redis://redis:6379
      AZURE_OPENAI_API_KEY: ${AZURE_OPENAI_API_KEY}
      AZURE_OPENAI_ENDPOINT: https://airops.openai.azure.com
      AZURE_OPENAI_DEPLOYMENT: gpt-4.1
      AZURE_OPENAI_API_VERSION: 2025-01-01-preview
      AZURE_OPENAI_EMBEDDING_DEPLOYMENT: text-embedding-ada-002
      AZURE_OPENAI_WHISPER_DEPLOYMENT: whisper
      # Additional AI Services
      FIRECRAWL_API_KEY: ${FIRECRAWL_API_KEY}
      # Zero-cache code reloads
      PYTHONDONTWRITEBYTECODE: 1
      PYTHONUNBUFFERED: 1

  frontend:
    build: ./frontend
    container_name: prsnl_frontend
    restart: unless-stopped
    ports:
      - "${FRONTEND_PORT:-3003}:3003"
    environment:
      PUBLIC_API_URL: http://backend:8000
      NODE_ENV: development
      PORT: 3003
    depends_on:
      - backend

volumes:
  postgres_data:
  redis_data:
  # LibreChat volumes
  librechat_uploads:
  librechat_logs:
  librechat_mongo_data:
  librechat_meili_data: