name: PRSNL
options:
  bundleIdPrefix: ai.prsnl
  deploymentTarget:
    iOS: 17.0
  xcodeVersion: 16.0

settings:
  base:
    SWIFT_VERSION: 5.0
    DEVELOPMENT_TEAM: ABC12DEF34 # Replace with your actual Team ID

targets:
  PRSNL:
    type: application
    platform: iOS
    deploymentTarget: 17.0
    sources: 
      - path: PRSNL
    entitlements:
      path: PRSNL/PRSNL.entitlements
      properties:
        com.apple.security.application-groups:
          - group.ai.prsnl.shared
    info:
      path: PRSNL/Info.plist
      properties:
        CFBundleDisplayName: PRSNL
        CFBundleShortVersionString: 1.0.0
        CFBundleVersion: 1
        UILaunchStoryboardName: LaunchScreen
        UISupportedInterfaceOrientations:
          - UIInterfaceOrientationPortrait
          - UIInterfaceOrientationLandscapeLeft
          - UIInterfaceOrientationLandscapeRight
        NSAppTransportSecurity:
          NSAllowsArbitraryLoads: false
          NSAllowsLocalNetworking: true
          NSExceptionDomains:
            localhost:
              NSExceptionAllowsInsecureHTTPLoads: true
        UIRequiredDeviceCapabilities:
          - arm64
          - metal
        UIBackgroundModes:
          - fetch
          - remote-notification
    settings:
      base:
        INFOPLIST_FILE: PRSNL/Info.plist
        CODE_SIGN_ENTITLEMENTS: PRSNL/PRSNL.entitlements
        PRODUCT_BUNDLE_IDENTIFIER: ai.prsnl
        SWIFT_ACTIVE_COMPILATION_CONDITIONS: DEBUG
    dependencies:
      - sdk: CoreData.framework
      - sdk: SwiftUI.framework
      - sdk: UIKit.framework
      - sdk: Foundation.framework
      - sdk: Security.framework
      - sdk: Accelerate.framework
      - sdk: Combine.framework
      - sdk: AVKit.framework
      - sdk: AVFoundation.framework
      - sdk: UserNotifications.framework
      - sdk: CoreSpotlight.framework

  PRSNLWidgets:
    type: app-extension
    platform: iOS
    deploymentTarget: 17.0
    sources: 
      - path: PRSNLWidgets
    entitlements:
      path: PRSNLWidgets/PRSNLWidgets.entitlements
      properties:
        com.apple.security.application-groups:
          - group.ai.prsnl.shared
    info:
      path: PRSNLWidgets/Info.plist
      properties:
        CFBundleDisplayName: PRSNLWidgets
        CFBundleShortVersionString: 1.0.0
        CFBundleVersion: 1
        NSExtension:
          NSExtensionPointIdentifier: com.apple.widgetkit-extension
    settings:
      base:
        INFOPLIST_FILE: PRSNLWidgets/Info.plist
        CODE_SIGN_ENTITLEMENTS: PRSNLWidgets/PRSNLWidgets.entitlements
        PRODUCT_BUNDLE_IDENTIFIER: ai.prsnl.widgets
        SWIFT_ACTIVE_COMPILATION_CONDITIONS: DEBUG
    dependencies:
      - target: PRSNL
      - sdk: WidgetKit.framework
      - sdk: SwiftUI.framework
      - sdk: CoreData.framework

  PRSNLShareExtension:
    type: app-extension
    platform: iOS
    deploymentTarget: 17.0
    sources: 
      - path: PRSNLShareExtension
    entitlements:
      path: PRSNLShareExtension/PRSNLShareExtension.entitlements
      properties:
        com.apple.security.application-groups:
          - group.ai.prsnl.shared
    info:
      path: PRSNLShareExtension/Info.plist
      properties:
        CFBundleDisplayName: Share to PRSNL
        CFBundleShortVersionString: 1.0.0
        CFBundleVersion: 1
        NSExtension:
          NSExtensionPointIdentifier: com.apple.share-services
          NSExtensionPrincipalClass: PRSNLShareExtension.ShareViewController
    settings:
      base:
        INFOPLIST_FILE: PRSNLShareExtension/Info.plist
        CODE_SIGN_ENTITLEMENTS: PRSNLShareExtension/PRSNLShareExtension.entitlements
        PRODUCT_BUNDLE_IDENTIFIER: ai.prsnl.shareextension
        SWIFT_ACTIVE_COMPILATION_CONDITIONS: DEBUG
    dependencies:
      - target: PRSNL
      - sdk: SwiftUI.framework
      - sdk: CoreData.framework

  PRSNLTests:
    type: bundle.unit-test
    platform: iOS
    deploymentTarget: 17.0
    sources:
      - path: PRSNLTests
    dependencies:
      - target: PRSNL
      - sdk: XCTest.framework
    settings:
      base:
        INFOPLIST_FILE: PRSNLTests/Info.plist
        PRODUCT_BUNDLE_IDENTIFIER: ai.prsnl.tests

schemes:
  PRSNL:
    build:
      targets:
        PRSNL: all
        PRSNLWidgets: all
        PRSNLShareExtension: all
    run:
      config: Debug
    profile:
      config: Release
    analyze:
      config: Debug
    archive:
      config: Release
