apiVersion: apps/v1
kind: Deployment
metadata:
  name: prsnl-backend
  labels:
    app: prsnl-backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: prsnl-backend
  template:
    metadata:
      labels:
        app: prsnl-backend
    spec:
      containers:
      - name: backend
        image: prsnl-backend:latest
        ports:
        - containerPort: 8000
        env:
        - name: DATABASE_URL
          value: "postgresql://prsnl:prsnl123@prsnl-postgres:5432/prsnl"
        - name: REDIS_URL
          value: "redis://prsnl-redis:6379"
        - name: AZURE_OPENAI_API_KEY
          value: "1U6RGbb4XrVh4LUqG5qrNLHd1hvHeCDqseSThAayqhclju9nUCtTJQQJ99BAACHYHv6XJ3w3AAABACOG6tdK"
        - name: AZURE_OPENAI_ENDPOINT
          value: "https://airops.openai.azure.com"
        - name: AZURE_OPENAI_DEPLOYMENT
          value: "gpt-4.1"
        - name: AZURE_OPENAI_API_VERSION
          value: "2025-01-01-preview"
        - name: AZURE_OPENAI_EMBEDDING_DEPLOYMENT
          value: "text-embedding-ada-002"
        - name: AZURE_OPENAI_WHISPER_DEPLOYMENT
          value: "whisper"
        livenessProbe:
          httpGet:
            path: /health
            port: 8000
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /health
            port: 8000
          initialDelaySeconds: 20
          periodSeconds: 5
---
apiVersion: v1
kind: Service
metadata:
  name: prsnl-backend
spec:
  selector:
    app: prsnl-backend
  ports:
  - port: 8000
    targetPort: 8000