apiVersion: apps/v1
kind: Deployment
metadata:
  name: prsnl-postgres
  labels:
    app: prsnl-postgres
spec:
  replicas: 1
  selector:
    matchLabels:
      app: prsnl-postgres
  template:
    metadata:
      labels:
        app: prsnl-postgres
    spec:
      containers:
      - name: postgres
        image: pgvector/pgvector:pg16
        ports:
        - containerPort: 5432
        env:
        - name: POSTGRES_DB
          value: "prsnl"
        - name: POSTGRES_USER
          value: "prsnl"
        - name: POSTGRES_PASSWORD
          value: "prsnl123"
        volumeMounts:
        - name: postgres-storage
          mountPath: /var/lib/postgresql/data
        - name: init-script
          mountPath: /docker-entrypoint-initdb.d/01-init.sql
          subPath: init.sql
      volumes:
      - name: postgres-storage
        persistentVolumeClaim:
          claimName: postgres-pvc
      - name: init-script
        configMap:
          name: postgres-init
---
apiVersion: v1
kind: Service
metadata:
  name: prsnl-postgres
spec:
  selector:
    app: prsnl-postgres
  ports:
  - port: 5432
    targetPort: 5432
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgres-pvc
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: postgres-init
data:
  init.sql: |
    -- Enable extensions
    CREATE EXTENSION IF NOT EXISTS vector;
    CREATE EXTENSION IF NOT EXISTS "uuid-ossp";
    CREATE EXTENSION IF NOT EXISTS "pg_trgm";
    
    -- Ensure user has proper permissions
    GRANT ALL PRIVILEGES ON DATABASE prsnl TO prsnl;